/**
 * Environment prefixes in GENERATED package.json scripts.
 *
 * npm and pnpm run scripts through cmd.exe on Windows, which knows no
 * `VAR=value command` form: it reads `NODE_ENV` as the program name and aborts
 * with "'NODE_ENV' is not recognized as an internal or external command"
 * (reported from a Windows laptop, 2026-09-16, on a project generated by lt
 * 1.47.0: `pnpm run start:local` died there).
 *
 * `cross-env` sets the variable in the child process instead, so the same script
 * works in bash, zsh, PowerShell and cmd.exe.
 */
/** Pinned exactly: an override target or dependency of ours is never a range (repo rule). */
export const CROSS_ENV_VERSION = '10.1.0';
export const CROSS_ENV_PACKAGE = 'cross-env';

/**
 * A POSIX env assignment in front of a command — the form cmd.exe cannot run.
 *
 * Deliberately NOT anchored to the start of the script: the mistake that actually
 * happens when converting is an `&&` chain in which only the first link was
 * wrapped (`cross-env NODE_ENV=x a && NODE_ENV=x b`), and an anchored expression
 * reports that as clean.
 */
export const ENV_PREFIX = /(^|[\s;&|(])[A-Z_][A-Z0-9_]*=\S/;

/** `cross-env` plus the assignments it carries — those are the covered ones. */
const CROSS_ENV_ASSIGNMENTS = /cross-env\s+(?:[A-Z_][A-Z0-9_]*=\S+\s+)+/g;

/**
 * Bare `VAR=value` prefixes in `script`, i.e. the ones cmd.exe would choke on.
 * Assignments that `cross-env` carries are removed first, so a correctly
 * converted script — including `cross-env A=1 B=2 cmd` — reports nothing.
 */
export function bareEnvPrefixes(script: string): string[] {
  const rest = script.replace(CROSS_ENV_ASSIGNMENTS, '');
  const found: string[] = [];
  for (const match of rest.matchAll(/(?:^|[\s;&|(])([A-Z_][A-Z0-9_]*=\S+)/g)) {
    found.push(match[1]);
  }
  return found;
}

/**
 * Make sure a generated project can run the scripts we just wrote.
 *
 * Lands in `dependencies`, NOT `devDependencies`: production trees are installed
 * without dev packages — the starter's Dockerfile uses
 * `pnpm install --frozen-lockfile --prod` and `pnpm deploy --prod` — and the scripts
 * run there (`start:prod`, `dp:prod` → `migrate:prod:up`) are exactly the env-carrying
 * ones. Measured by the starter session on two real `--prod` installs from one
 * lockfile: as a devDependency `node_modules/.bin/cross-env` is missing, as a
 * dependency it is there. (The framework repos keep it in devDependencies: their
 * scripts never reach a customer image, and nest-server is published to npm, where a
 * production dependency would be forced on every consumer.)
 *
 * Only added when the project does not declare it anywhere already — the starters ship
 * it themselves, and a second entry would fight theirs on every update. An existing
 * entry keeps its group and version, devDependencies included.
 *
 * @param pkg Parsed package.json of the generated project; mutated in place.
 * @returns true when the dependency was added.
 */
export function ensureCrossEnvDependency(pkg: Record<string, any>): boolean {
  const declared = [pkg.dependencies, pkg.devDependencies, pkg.peerDependencies, pkg.optionalDependencies].some(
    (group) => group && typeof group === 'object' && CROSS_ENV_PACKAGE in group,
  );
  if (declared) {
    return false;
  }
  if (!pkg.dependencies || typeof pkg.dependencies !== 'object') {
    pkg.dependencies = {};
  }
  pkg.dependencies[CROSS_ENV_PACKAGE] = CROSS_ENV_VERSION;
  pkg.dependencies = Object.fromEntries(
    Object.entries(pkg.dependencies as Record<string, string>).sort(([a], [b]) => a.localeCompare(b)),
  );
  return true;
}

/** True when `script` still carries a bare `VAR=value` prefix. */
export function usesPosixEnvPrefix(script: string): boolean {
  return bareEnvPrefixes(script).length > 0;
}

/**
 * Prefix a command with `cross-env VAR=value …`.
 *
 * @param env     Variables to set, e.g. `{ NODE_ENV: 'production' }`.
 * @param command The command to run.
 */
export function withCrossEnv(env: Record<string, string>, command: string): string {
  const assignments = Object.entries(env)
    .map(([name, value]) => `${name}=${value}`)
    .join(' ');
  return `cross-env ${assignments} ${command}`;
}
