import { readFileSync } from 'fs';
import { join, relative } from 'path';
import * as ts from 'typescript';

import { bareEnvPrefixes, ensureCrossEnvDependency, usesPosixEnvPrefix, withCrossEnv } from '../src/lib/cross-env';

const SRC = join(__dirname, '..', 'src');

/**
 * npm and pnpm run package.json scripts through cmd.exe on Windows. The existing
 * `package-scripts-portable.test.ts` keeps THIS repo's own scripts portable; this
 * one covers the scripts the CLI WRITES INTO GENERATED PROJECTS, which is where a
 * `NODE_ENV=…` prefix actually reached users: a project generated by lt 1.47.0
 * could not run `pnpm run start:local` or the `migrate:<env>:up` scripts on
 * Windows at all.
 */
interface GeneratedScript {
  file: string;
  line: number;
  text: string;
}

/**
 * Every `scripts['name'] = '<command>'` assignment in the CLI's own sources, read
 * from the AST rather than by regex: a template literal spans lines and carries
 * `${…}` holes, and both forms are used here. Each hole becomes `X`, which is
 * enough for the shape checks below.
 */
function collectGeneratedScripts(): GeneratedScript[] {
  const files = ts.sys
    .readDirectory(SRC, ['.ts'], ['templates'])
    .filter((file) => !file.endsWith('.d.ts') && !file.includes('/lib/cross-env.ts'));
  const scripts: GeneratedScript[] = [];

  for (const file of files) {
    const source = ts.createSourceFile(file, readFileSync(file, 'utf8'), ts.ScriptTarget.Latest, true);
    const visit = (node: ts.Node): void => {
      if (
        ts.isBinaryExpression(node) &&
        node.operatorToken.kind === ts.SyntaxKind.EqualsToken &&
        ts.isElementAccessExpression(node.left) &&
        /(^|\.)scripts$/.test(node.left.expression.getText(source))
      ) {
        const text = literalText(node.right, source);
        if (text !== null) {
          scripts.push({
            file: relative(join(SRC, '..'), file),
            line: source.getLineAndCharacterOfPosition(node.getStart(source)).line + 1,
            text,
          });
        }
      }
      ts.forEachChild(node, visit);
    };
    visit(source);
  }
  return scripts;
}

/** The text of a string or template literal, with every `${…}` replaced by `X`. */
function literalText(node: ts.Node, source: ts.SourceFile): null | string {
  if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) {
    return node.text;
  }
  if (ts.isTemplateExpression(node)) {
    return node.head.text + node.templateSpans.map((span) => `X${span.literal.text}`).join('');
  }
  if (ts.isBinaryExpression(node) && node.operatorToken.kind === ts.SyntaxKind.PlusToken) {
    const left = literalText(node.left, source);
    const right = literalText(node.right, source);
    return left === null || right === null ? null : left + right;
  }
  return null;
}

describe('scripts the CLI writes into generated projects', () => {
  const scripts = collectGeneratedScripts();

  it('finds the generated scripts at all — the checks below must not be vacuous', () => {
    expect(scripts.length).toBeGreaterThanOrEqual(8);
    expect(scripts.some((s) => s.text.includes('migrate'))).toBe(true);
  });

  it('never writes a bare VAR=value prefix — cmd.exe reads it as a command name', () => {
    const offenders = scripts
      .filter((s) => usesPosixEnvPrefix(s.text))
      .map((s) => `${s.file}:${s.line} ${bareEnvPrefixes(s.text).join(', ')}`);
    expect(offenders).toEqual([]);
  });

  it('never writes `|| true` or a /dev/null redirect', () => {
    const offenders = scripts
      .filter((s) => /\|\|\s*true\b/.test(s.text) || s.text.includes('/dev/null'))
      .map((s) => `${s.file}:${s.line} ${s.text}`);
    expect(offenders).toEqual([]);
  });

  it('keeps the POSIX-shell-function scripts to the one known gap', () => {
    // `f() { … }; f` is how `migrate:create` forwards its argument. cmd.exe cannot
    // run it, and unlike the env prefix it has no drop-in replacement, so it stays
    // a known Windows gap (M2). This test exists so a SECOND one cannot appear
    // unnoticed.
    const shellFunctions = scripts.filter((s) => /\w+\(\)\s*\{/.test(s.text));
    expect(shellFunctions.map((s) => s.text.slice(0, 20))).toEqual(['f() { node ./bin/mig', 'f() { migrate create']);
  });
});

describe('cross-env helpers', () => {
  it('wraps a command, including several variables', () => {
    expect(withCrossEnv({ NODE_ENV: 'production' }, 'migrate up')).toBe('cross-env NODE_ENV=production migrate up');
    expect(withCrossEnv({ A: '1', B: '2' }, 'cmd')).toBe('cross-env A=1 B=2 cmd');
  });

  describe('detector', () => {
    it('reports a chain in which only the first link is wrapped', () => {
      // The conversion mistake that actually happens. An expression anchored to
      // the start of the script reports this as clean.
      expect(bareEnvPrefixes('cross-env NODE_ENV=test a && NODE_ENV=test b')).toEqual(['NODE_ENV=test']);
      expect(usesPosixEnvPrefix('a && B=1 b')).toBe(true);
      expect(usesPosixEnvPrefix('a; B=1 b')).toBe(true);
    });

    it('accepts a properly wrapped command', () => {
      expect(bareEnvPrefixes('cross-env NODE_ENV=production node ./bin/migrate.js up')).toEqual([]);
      expect(usesPosixEnvPrefix('cross-env A=1 B=2 cmd && cross-env C=3 other')).toBe(false);
      expect(usesPosixEnvPrefix('rimraf --glob "./dist/*.map"')).toBe(false);
    });
  });

  describe('ensureCrossEnvDependency', () => {
    it('adds an exact pin to dependencies — a --prod install must keep it', () => {
      // Production trees are installed without dev packages (`pnpm install --prod`,
      // `pnpm deploy --prod`), and `start:prod` / `dp:prod` run the env-carrying
      // scripts there. In devDependencies cross-env is simply absent.
      const pkg: Record<string, any> = { dependencies: { rxjs: '7.8.2', bcrypt: '6.0.0' }, devDependencies: { rimraf: '6.0.1' } };
      expect(ensureCrossEnvDependency(pkg)).toBe(true);
      expect(pkg.dependencies['cross-env']).toMatch(/^\d+\.\d+\.\d+$/);
      expect(Object.keys(pkg.dependencies)).toEqual(['bcrypt', 'cross-env', 'rxjs']);
      expect(pkg.devDependencies).toEqual({ rimraf: '6.0.1' });
    });

    it('never adds a second entry next to the starter\'s own', () => {
      // Including an entry the starter keeps in devDependencies: it stays there,
      // with its own version. Moving it would fight the starter on every update.
      for (const group of ['dependencies', 'devDependencies', 'peerDependencies', 'optionalDependencies']) {
        const pkg: Record<string, any> = { [group]: { 'cross-env': '7.0.3' } };
        expect(ensureCrossEnvDependency(pkg)).toBe(false);
        expect(pkg[group]['cross-env']).toBe('7.0.3');
        expect(Object.keys(pkg)).toEqual([group]);
      }
    });

    it('creates the block when the package has none', () => {
      const pkg: Record<string, any> = { name: 'api' };
      expect(ensureCrossEnvDependency(pkg)).toBe(true);
      expect(Object.keys(pkg.dependencies)).toEqual(['cross-env']);
      expect(pkg.devDependencies).toBeUndefined();
    });
  });
});
