name: Publish

on:
  release:
    types:
      - released

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Node 14.6
        uses: actions/setup-node@v1
        with:
          node-version: 14.6
      - name: NPM install
        run: npm install
      - name: Build
        run: npm build
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
